version: "3.7"

services:
  rest-api:
    build: .
    ports:
      - 80:80
    volumes:
      - ./reticulas/reticulas:/var/www/html/reticulas
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
      - ./reticulas/reticulas.sql:/docker-entrypoint-initdb.d/reticulas.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: reticulas
